name: Lint-Unit-Test

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      
jobs:
  Lints:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.7.1"]

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Install poetry
        run: echo "This is not good"
